In [2]:
import pandas as pd
a=pd.Series([1,2,3])
print(a)


0    1
1    2
2    3
dtype: int64


In [5]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))



[1 2 3]
<class 'numpy.ndarray'>


In [6]:
import numpy as np
arr=np.arange(11)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)


(2, 3)


In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr2=arr.reshape(3,2)
print(arr2)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
import numpy as np
arr=np.array([1,2,36,7,8,10,2,3,4,5,6,7,8,9,10,2,3,4,5,6,7,8,9,12,13,15,16,13,14,12,14,17,91,89,78,67])
arr2=arr.reshape(6,6)
print(arr2)


[[ 1  2 36  7  8 10]
 [ 2  3  4  5  6  7]
 [ 8  9 10  2  3  4]
 [ 5  6  7  8  9 12]
 [13 15 16 13 14 12]
 [14 17 91 89 78 67]]


In [18]:
import numpy as np
arr=np.arange(30)
arr2=arr.reshape(6,5)
print(arr2)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [20]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr.shape=(2,5)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
import pandas as pd
dict={"d":1,"m":2,"t":3}
arr=pd.Series(dict)
print(arr)

d    1
m    2
t    3
dtype: int64


In [24]:
print(type(dict))

<class 'dict'>


In [14]:
import pandas as pd
a=pd.read_csv("Book1.csv")
print(a)

     NAME  AGE  SALARY
0  geetha   13   10000
1   laxmi   14   20000
2  anitha   15   30000
3  rupika   16   40000


In [15]:
a["AGE"]

0    13
1    14
2    15
3    16
Name: AGE, dtype: int64

In [33]:
a[["NAME","SALARY"]]

NAME  SALARY
0  geetha   10000
1   laxmi   20000
2  anitha   30000
3  rupika   40000

In [34]:
a.head(2)

NAME  AGE  SALARY
0  geetha   13   10000
1   laxmi   14   20000

In [35]:
a.tail(3)

NAME  AGE  SALARY
1   laxmi   14   20000
2  anitha   15   30000
3  rupika   16   40000

In [36]:
a.head()

NAME  AGE  SALARY
0  geetha   13   10000
1   laxmi   14   20000
2  anitha   15   30000
3  rupika   16   40000

In [37]:
a

NAME  AGE  SALARY
0  geetha   13   10000
1   laxmi   14   20000
2  anitha   15   30000
3  rupika   16   40000

In [16]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
NAME      4 non-null object
AGE       4 non-null int64
SALARY    4 non-null int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes


In [40]:
a["AGE"]>30

0    False
1    False
2    False
3    False
Name: AGE, dtype: bool

In [41]:
a[a["AGE"]>30]

Empty DataFrame
Columns: [NAME, AGE, SALARY]
Index: []

In [42]:
 a["AGE"].max()

16

In [17]:
type(a)

pandas.core.frame.DataFrame

In [18]:
a[a["AGE"]>10]

NAME  AGE  SALARY
0  geetha   13   10000
1   laxmi   14   20000
2  anitha   15   30000
3  rupika   16   40000

In [45]:
a["AGE"].min()

13

In [46]:
a["AGE"].sum()

58

In [47]:
a["NAME"].max()

'rupika'

In [48]:
a["NAME"].min()

'anitha'

In [49]:
a["NAME"].sum()

'geethalaxmianitharupika'

In [19]:
a[["NAME","SALARY","AGE"]].max()

NAME      rupika
SALARY     40000
AGE           16
dtype: object

In [20]:
 a.loc[1]

NAME      laxmi
AGE          14
SALARY    20000
Name: 1, dtype: object

In [53]:
print(a.loc[2])

NAME      anitha
AGE           15
SALARY     30000
Name: 2, dtype: object


In [21]:
print(a.loc[a["AGE"]>12])

     NAME  AGE  SALARY
0  geetha   13   10000
1   laxmi   14   20000
2  anitha   15   30000
3  rupika   16   40000


In [22]:
a["ADDRESS"]=["a","b","c","d"]

In [23]:
print(a)

     NAME  AGE  SALARY ADDRESS
0  geetha   13   10000       a
1   laxmi   14   20000       b
2  anitha   15   30000       c
3  rupika   16   40000       d


In [25]:
a["MARKS"]=0
print(a)

     NAME  AGE  SALARY ADDRESS  MARKS
0  geetha   13   10000       a      0
1   laxmi   14   20000       b      0
2  anitha   15   30000       c      0
3  rupika   16   40000       d      0


In [59]:
a.loc[1,"NAME"]

'laxmi'

In [27]:
a1=[a[(a.AGE>13)&(a.SALARY>20000)]]
print(a1)

[     NAME  AGE  SALARY ADDRESS  MARKS
2  anitha   15   30000       c      0
3  rupika   16   40000       d      0]


In [3]:
import pandas as pd
data=pd.read_csv("1000 Sales Records.csv")
data

Region               Country   Item Type  \
0    Middle East and North Africa                 Libya   Cosmetics   
1                   North America                Canada  Vegetables   
2    Middle East and North Africa                 Libya   Baby Food   
3                            Asia                 Japan      Cereal   
4              Sub-Saharan Africa                  Chad      Fruits   
..                            ...                   ...         ...   
995  Middle East and North Africa            Azerbaijan      Snacks   
996                        Europe               Georgia   Baby Food   
997  Middle East and North Africa  United Arab Emirates  Vegetables   
998                        Europe               Finland   Household   
999                        Europe              Portugal      Cereal   

    Sales Channel Order Priority  Order Date   Order ID   Ship Date  \
0         Offline              M  10/18/2014  686800706  10/31/2014   
1          Online              M   11/7/2011  185941302   12/8/2011   
2         Offline              C  10/31/2016  246222341   12/9/2016   
3         Offline              C   4/10/2010  161442649   5/12/2010   
4         Offline              H   8/16/2011  645713555   8/31/2011   
..            ...            ...         ...        ...         ...   
995       Offline              C   4/18/2010  534085166   4/25/2010   
996       Offline              H    8/1/2011  590768182    9/7/2011   
997        Online              C   5/12/2011  524363124   6/28/2011   
998       Offline              L   1/25/2016  289606320   2/14/2016   
999       Offline              C   4/10/2014  811546599    5/8/2014   

     Units Sold  Unit Price  Unit Cost  Total Revenue  Total Cost  \
0          8446      437.20     263.33     3692591.20  2224085.18   
1          3018      154.06      90.93      464953.08   274426.74   
2          1517      255.28     159.42      387259.76   241840.14   
3          3322      205.70     117.11      683335.40   389039.42   
4          9845        9.33       6.92       91853.85    68127.40   
..          ...         ...        ...            ...         ...   
995        6524      152.58      97.44      995431.92   635698.56   
996         288      255.28     159.42       73520.64    45912.96   
997        9556      154.06      90.93     1472197.36   868927.08   
998        9801      668.27     502.54     6549714.27  4925394.54   
999        3528      205.70     117.11      725709.60   413164.08   

     Total Profit  
0      1468506.02  
1       190526.34  
2       145419.62  
3       294295.98  
4        23726.45  
..            ...  
995     359733.36  
996      27607.68  
997     603270.28  
998    1624319.73  
999     312545.52  

[1000 rows x 14 columns]

In [5]:
data.head()

Region Country   Item Type Sales Channel  \
0  Middle East and North Africa   Libya   Cosmetics       Offline   
1                 North America  Canada  Vegetables        Online   
2  Middle East and North Africa   Libya   Baby Food       Offline   
3                          Asia   Japan      Cereal       Offline   
4            Sub-Saharan Africa    Chad      Fruits       Offline   

  Order Priority  Order Date   Order ID   Ship Date  Units Sold  Unit Price  \
0              M  10/18/2014  686800706  10/31/2014        8446      437.20   
1              M   11/7/2011  185941302   12/8/2011        3018      154.06   
2              C  10/31/2016  246222341   12/9/2016        1517      255.28   
3              C   4/10/2010  161442649   5/12/2010        3322      205.70   
4              H   8/16/2011  645713555   8/31/2011        9845        9.33   

   Unit Cost  Total Revenue  Total Cost  Total Profit  
0     263.33     3692591.20  2224085.18    1468506.02  
1      90.93      464953.08   274426.74     190526.34  
2     159.42      387259.76   241840.14     145419.62  
3     117.11      683335.40   389039.42     294295.98  
4       6.92       91853.85    68127.40      23726.45

# data frame

In [29]:
d={
    "a":[1,2,3],
    "b":[4,5,6],
    "c":[7,8,9]
}
x=pd.DataFrame(d)
print(x)

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9


In [31]:
pd.options.display.max_rows

60

In [32]:
x.loc[1]

a    2
b    5
c    8
Name: 1, dtype: int64

In [33]:
x.loc[[0,1]]

a  b  c
0  1  4  7
1  2  5  8

In [34]:
pd.options.display.min_rows

10

In [35]:
pd.options.display.max_rows

60