In [2]:
aimport pandas as pd
a=pd.Series([1,2,3])
print(a)


0    1
1    2
2    3
dtype: int64


In [5]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))



[1 2 3]
<class 'numpy.ndarray'>


In [6]:
import numpy as np
arr=np.arange(11)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)


(2, 3)


In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr2=arr.reshape(3,2)
print(arr2)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
import numpy as np
arr=np.array([1,2,36,7,8,10,2,3,4,5,6,7,8,9,10,2,3,4,5,6,7,8,9,12,13,15,16,13,14,12,14,17,91,89,78,67])
arr2=arr.reshape(6,6)
print(arr2)


[[ 1  2 36  7  8 10]
 [ 2  3  4  5  6  7]
 [ 8  9 10  2  3  4]
 [ 5  6  7  8  9 12]
 [13 15 16 13 14 12]
 [14 17 91 89 78 67]]


In [18]:
import numpy as np
arr=np.arange(30)
arr2=arr.reshape(6,5)
print(arr2)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [20]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr.shape=(2,5)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
import pandas as pd
dict={"d":1,"m":2,"t":3}
arr=pd.Series(dict)
print(arr)

d    1
m    2
t    3
dtype: int64


In [24]:
print(type(dict))

<class 'dict'>


In [28]:
import pandas as pd
a=pd.read_csv("Book1.csv")
print(a)

     NAME  AGE  SALARY
0  geetha   13   10000
1   laxmi   14   20000
2  anitha   15   30000
3  rupika   16   40000


In [30]:
a["AGE"]

0    13
1    14
2    15
3    16
Name: AGE, dtype: int64

In [33]:
a[["NAME","SALARY"]]

NAME  SALARY
0  geetha   10000
1   laxmi   20000
2  anitha   30000
3  rupika   40000

In [34]:
a.head(2)

NAME  AGE  SALARY
0  geetha   13   10000
1   laxmi   14   20000

In [35]:
a.tail(3)

NAME  AGE  SALARY
1   laxmi   14   20000
2  anitha   15   30000
3  rupika   16   40000

In [36]:
a.head()

NAME  AGE  SALARY
0  geetha   13   10000
1   laxmi   14   20000
2  anitha   15   30000
3  rupika   16   40000

In [37]:
a

NAME  AGE  SALARY
0  geetha   13   10000
1   laxmi   14   20000
2  anitha   15   30000
3  rupika   16   40000

In [38]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
NAME      4 non-null object
AGE       4 non-null int64
SALARY    4 non-null int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes


In [40]:
a["AGE"]>30

0    False
1    False
2    False
3    False
Name: AGE, dtype: bool

In [41]:
a[a["AGE"]>30]

Empty DataFrame
Columns: [NAME, AGE, SALARY]
Index: []

In [42]:
a["AGE"].max()

16

In [43]:
type(a)

pandas.core.frame.DataFrame

In [44]:
a[a["AGE"]>10]

NAME  AGE  SALARY
0  geetha   13   10000
1   laxmi   14   20000
2  anitha   15   30000
3  rupika   16   40000

In [45]:
a["AGE"].min()

13

In [46]:
a["AGE"].sum()

58

In [47]:
a["NAME"].max()

'rupika'

In [48]:
a["NAME"].min()

'anitha'

In [49]:
a["NAME"].sum()

'geethalaxmianitharupika'

In [50]:
a[["NAME","SALARY","AGE"]].max()

NAME      rupika
SALARY     40000
AGE           16
dtype: object