In [2]:
import numpy as np
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [8]:
import numpy as np
print(np.__version__)


1.16.5


In [6]:
import numpy as np

print(np.__version__)


1.16.5


In [10]:
arr=np.arange(18).reshape(3,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [18]:
arr=np.array((1,2,3,4))
print(arr.ndim)

1


In [17]:
import numpy as np

arr = np.array(42)

print(arr.ndim)

0


In [16]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)

2


In [19]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr.ndim)

3


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[-1])

4


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[-1] + arr[3])

8


In [7]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[1,3])

2nd element on 1st row:  9


In [8]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [13]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [11]:
 import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 1, 2])


12


In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [1]:
import numpy as np
d=np.arange(1,20,2)
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [3]:
e=np.ones(5)
e

array([1., 1., 1., 1., 1.])

In [4]:
f=np.zeros(5)
f

array([0., 0., 0., 0., 0.])

In [5]:
g=np.empty(3)
g

array([6.01347002e-154, 6.96742065e+252, 7.20366915e+159])

In [10]:
h=np.array([[1,2,3],[4,5,6]])
h

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
h[0]

array([1, 2, 3])

In [12]:
h[0,1]

2

In [13]:
h[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
h[0:1,1:2]

array([[2]])

In [23]:
i=np.array([[1,2,3],[4,5,6],[7,8,9]])
i

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
i.dtype

dtype('int32')

In [20]:
f.dtype

dtype('float64')

In [24]:
print(len(i))

3


In [27]:
j=d.reshape(2,5)
j

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [28]:
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
import numpy as np
k=np.linspace(2,25,6)
k

array([ 2. ,  6.6, 11.2, 15.8, 20.4, 25. ])

In [42]:
a=([1,2,3])
b=([4,5,6])
l=a+b
l

[1, 2, 3, 4, 5, 6]

In [49]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [52]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
x=np.array(["banana","cherry","apple"])
np.sort(x)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [54]:
y=([1,4,3,20])
print(np.sort(y))

[ 1  3  4 20]


In [55]:
d=np.array([[3,2,4],[5,0,1]])
np.sort(d)

array([[2, 3, 4],
       [0, 1, 5]])